### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by 6a5h4** [tien/pi-hole-connect#98] opened 2022-04-22 11:02 UTC
**Describe the bug**

Since last pihole update yesterday, this app can not connect anymore. Testet with 2 piholes. Both has the same api issue now.
Re-inserting the api-key do not solve it.

**To Reproduce**
Steps to reproduce the behaviour:
Since last pihole update yesterday, this app can not connect anymore. Testet with 2 piholes. Both has the same api issue now.
Re-inserting the api-key do not solve it.

**Expected behaviour**
Since last pihole update yesterday, this app can not connect anymore. Testet with 2 piholes. Both has the same api issue now.
Re-inserting the api-key do not solve it.

**Screenshots**

**Smartphone (please complete the following information):**

**Additional context**
Since last pihole update yesterday, this app can not connect anymore. Testet with 2 piholes. Both has the same api issue now.
Re-inserting the api-key do not solve it.

**Comment by tien** [comment] 2022-04-22 12:12
@6a5h4 might be a duplicate of #95 and is already fixed. Can you check whether the latest release has a working home screen? Log screen error is due to a bug from pi.hole and need to be fixed by them

**Comment by 6a5h4** [comment] 2022-04-22 13:12
No it is not the same. Ist says connection error. Check internet connection or api-key.
Ist can not connect anymore to the pihole api so i get no data displayed anymore.
Before i had updated both pihole DNS yesterday both pihole api's was working well.
Now all pages on your app are NOT working. This is YOUR mistake. Fix the error now...

The piholes are working fine. 
Your app is not working now.

**Comment by Dirty-Racoon** [comment] 2022-05-22 22:08
Good evening. I just updated pi-hole to the most current version of pi-hole as of 5-22-2022 
Version: 5.10
FTL: 5.15
Web interface: 5.12
The app is currently up to date as well. I experienced this same issue
![Screenshot_20220522-180317_Pi-hole Connect](https://user-images.githubusercontent.com/20018978/169717874-9da93191-9c62-44fd-8eb7-ec594d42ac78.jpg)
I have tried removing the old configuration in the app and adding my pi-hole from scratch. That still won't fix it. 
I am still able to enable/disable, see statistics but as soon as I head to the logs it throws the error. 

I'd like end by saying I did send you some money because I really appreciate the work you put into this. It's a great app and I love the functionality of it.

**Comment by stalkerGH** [comment] 2022-06-28 16:49
This is a fix which I found in another app - it works for me in Pi Hole Connect too: https://github.com/sterrenburg/flutterhole/issues/159#issuecomment-1113652973

**Comment by iceandrews** [comment] 2022-09-03 00:47
I'm having the same issue.

**Comment by Dirty-Racoon** [comment] 2022-09-03 01:23
> I'm having the same issue.

[Follow this link ](https://github.com/sterrenburg/flutterhole/issues/159#issuecomment-1113652973) 

It fixed my issue.

**Comment by Zobby31** [comment] 2022-09-04 09:26
The issue has made its come-back with the last version of pi-hole (5.12).
Moreover, the fix mentionned above do not work anymore.

**Comment by iceandrews** [comment] 2022-09-04 22:09
Yeah, it's back again, even flutterhole has the same problem.

**Comment by tien** [comment] 2022-09-07 10:17
Weird, seem to work fine for me on the latest version. The problem was actually with AdminLTE, the version I'm on `v5.14.2` is working as expected.

**Comment by iceandrews** [comment] 2022-09-07 13:49
Yes it was fixed with https://github.com/pi-hole/AdminLTE/commit/d68d5eee9a9c03c559aabb569c1a2cd18c60dafa

This isn't a bug anymore.

**Closed** 2022-09-07 18:28 UTC
Labels: bug
